accessories/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from accessories import views

app_name = 'Accessories'

urlpatterns = [
    url(r'^$', views.accessories_list, name='accessories_list'),
    url(r'^(?P<ids>\d+)/$', views.accessories_details, name='accessories_details'),
    url(r'^(?P<ids>\d+)/original', views.accessories_original_details, name='accessories_original_details'),
    url(r'^(?P<ids>\d+)/update/$', views.accessories_update, name='accessories_update'),
    url(r'^(?P<ids>\d+)/delete/$', views.accessories_delete, name='accessories_delete'),
    url(r'^(?P<ids>\d+)/checked/$', views.accessories_checked, name='accessories_checked'),

    url(r'^incomplete$', views.incomplete_list, name='incomplete_list'),
    url(r'^complete$', views.complete_list, name='complete_list'),
    url(r'^share/photo$', views.share_photo, name='share_photo'),
]

stomger/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from stomger.views import dashboard

app_name = 'Stomger'

urlpatterns = [
    url(r'^$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard$', dashboard, name='dashboard'),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^accessories/', include('accessories.urls')),
]

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-default navbar-static-top m-b-0">
    <div class="navbar-header">
        <a class="navbar-toggle hidden-sm hidden-md hidden-lg "
           href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse">
            <i class="ti-menu"></i>
        </a>

        <div class="top-left-part">
            <a class="logo" href="{% url 'dashboard' %}">
                <b>
                    <img src="{% static 'plugins/images/logo.png' %}" alt="Anasayfa"/>
                </b>
                <span class="hidden-xs"><strong>STOCK</strong>MANAGER</span>
            </a>
        </div>

        <ul class="nav navbar-top-links navbar-left hidden-xs">
            <li>
                <a href="javascript:void(0)" class="open-close hidden-xs waves-effect waves-light">
                    <i class="icon-arrow-left-circle ti-menu"></i>
                </a>
            </li>
            <li>
                <form role="search" class="app-search hidden-xs">
                    <input type="text" placeholder="Search" class="form-control">
                    <a href=""><i class="fa fa-search"></i></a>
                </form>
            </li>
        </ul>

        <ul class="nav navbar-top-links navbar-right pull-right">
            <!-- /.dropdown -->
            <li class="dropdown">
                {% if not request.user.is_authenticated %}
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                        <b class="hidden-xs">Welcome!</b>
                    </a>
                {% else %}
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                        <b class="hidden-xs">Welcome, {{ request.user.username }}!</b>
                    </a>
                    <ul class="dropdown-menu dropdown-user animated flipInY">
                        <li><a href="/admin/auth/user/{{ request.user.id }}/change/"><i class="ti-settings"></i> Account Settings</a></li>
                        <li><a href="{% url 'logout' %}"><i class="fa fa-power-off"></i> Logout</a></li>
                    </ul>
                {% endif %}
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
    </div>
    <!-- /.navbar-header -->
    <!-- /.navbar-top-links -->
    <!-- /.navbar-static-side -->
</nav>

templates/partials/sidebar.html
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse slimscrollsidebar">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search hidden-sm hidden-md hidden-lg">
                <!-- input-group -->
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Ara...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>

            <li class="nav-small-cap m-t-10">--- Menu</li>
            <li><a href="{% url 'dashboard' %}" class="waves-effect">
                <i class="fa fa-dashboard"></i>&nbsp;&nbsp;
                <span class="hide-menu">Dashboard </span></a>
            </li>
            <li><a href="javascript:void(0);" class="waves-effect">
                <i class="fa fa-flickr"></i>&nbsp;&nbsp;
                <span class="hide-menu">Accessories</span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{% url 'Accessories:accessories_list' %}">All</a>
                    </li>
                    <li>
                        <a href="{% url 'Accessories:complete_list' %}">Complete</a>
                    </li>
                    <li>
                        <a href="{% url 'Accessories:incomplete_list' %}">Incomplete</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>